CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'bdurmus'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'bdurmus'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';
FLUSH PRIVILEGES;
