CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'bdurmus'@'%' IDENTIFIED BY 'root123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'bdurmus'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';
